### PR TITLE
Fix for compiling with kernel 4.11.9

### PR DESCRIPTION
**Pull request by zebulon2**
Patch for compiling with kernel 4.11.9 and 4.12+. This patch was taken from kernel developer Stephen Rothwell. See LKML post https://patchwork.kernel.org/patch/9773573/ for details.

### CODE REVIEW

**Comment by CGarces** [comment]
@zebulon2 Try to squash on single commit.

**Comment by MilhouseVH** [comment]
@zebulon2: Just a nit, but this codebase puts spaces around the condition and major/minor/bug elements - might be best to maintain that style for consistency...
```
-#if (LINUX_VERSION_CODE>=KERNEL_VERSION(4,11,9))
+#if (LINUX_VERSION_CODE >= KERNEL_VERSION(4, 11, 9))
```

**Comment by MilhouseVH** [comment]
@zebulon2 I don't know what's going on here now, this pull seems to have become a little confused. It might be easier if you close this and @paspro can merge #5 instead. Thanks.

**Comment by CGarces** [comment]
Hi @zebulon2 
Your repo only have a single branch (v.5.1.5) all the commits that you are doing goes to all your PR like this one or https://github.com/astsam/rtl8812au/pull/47
Please check how create several branches on your repository and use one branch for each PR. Also use one PR for a single functionality.
Also learn how squash commits to send more clean PR to other forks.

**Comment by zebulon2** [comment]
Apologies for the issues, will do better practice next time. Closing this as this pull request is being replaced.

**Pull request closed without merging**
