### PR TITLE
Add kernel v4.11.9 support

### PR DESCRIPTION
**Pull request by MilhouseVH**
Replacement for #1 which seems to have got a little confused.

@zebulon2 sorry (and thanks).

### CODE REVIEW

**Comment by zebulon2** [comment]
No problem. Actually, there is another patch for the same issue here https://github.com/gordboy/rtl8812au/commit/23cc0dbbd37ff7d45d9a7a167b34ccba0fe70b99. This one sets `mon_ndev->needs_free_netdev = true;` in os_dep/linux/ioctl_cfg80211.c and correctly calls the destructor in os_dep/linux/os_intfs.c. Would not this be more suitable?

**Comment by MilhouseVH** [comment]
I don't see it makes much difference. The more important issue is that this repo looks to be dead already.

**Comment by zebulon2** [comment]
Which repo?

**Comment by MilhouseVH** [comment]
This repo. The one you are commenting on.

The lack of interest/activity from the repo owner (@paspro) in terms of reviewing/merging pull requests is usually a good sign that things aren't going well with the general "health" of the repository (which as it stands won't build for kernels >= 4.11.9). He could be on holiday of course, in which case I've jumped the gun (apologies) but I'm just seeing this everywhere with these repositories, so it wouldn't surprise me if I'm 100% correct.

**Comment by MilhouseVH** [comment]
Thanks @paspro - very glad to see you're still alive and well! :)

Apologies for casting aspersions, but having dealt with numerous rtl8812au-type repositories it's not unusual for a new fork to be created, which is maintained for a short while (until the owners itch has been scratched) and then left to rot.

**Pull request merged**
